import type { PluginManifest } from './types'

// Phase 35: the built-in plugin registry (static manifests; diagnostics run live).
// Permissions describe the access each plugin WOULD need once an execution runtime
// exists — none of it is granted or exercised in this phase.

export const BUILTIN_PLUGINS: PluginManifest[] = [
  {
    id: 'opencode-agent',
    name: 'OpenCode CLI',
    version: '1.0.0',
    kind: 'agent',
    description: 'OpenCode runs locally behind Workspace and Goal. Its streamed events are rendered as one conversational project-editing flow.',
    status: 'planned',
    permissions: ['terminal_read', 'terminal_write', 'filesystem_read', 'git_read'],
    docsUrl: 'docs/phase-37-sidebar-chat-opencode-gaia.md',
    safetyNotes: [
      'Workspace and Goal stay scoped to the selected project directory.',
      'OpenCode Go login is interactive (opencode auth login); Akorith never stores or prints tokens.'
    ],
    builtIn: true
  },
  {
    id: 'github-workbench',
    name: 'GitHub Workbench',
    version: '0.1.0',
    kind: 'integration',
    description: 'Pull requests, issues, and checks as a read-first workbench panel. Phase 35 diagnoses the GitHub CLI only.',
    status: 'planned',
    permissions: ['git_read', 'network'],
    safetyNotes: ['No mutations in Phase 35.', 'Future writes would be explicit and per-action.'],
    builtIn: true
  },
  {
    id: 'remote-ollama-telemetry',
    name: 'Remote Ollama Telemetry',
    version: '0.1.0',
    kind: 'telemetry',
    description: 'A secured companion that reports remote GPU/VRAM so the Dashboard can show off-machine runtimes. Phase 35 checks local Ollama tooling and configured remote profiles.',
    status: 'planned',
    permissions: ['network', 'model_runtime'],
    safetyNotes: ['No public exposure.', 'Remote GPU telemetry needs a secured companion endpoint (future).'],
    builtIn: true
  },
  {
    id: 'hermes-memory',
    name: 'Hermes Memory / Skills',
    version: '0.1.0',
    kind: 'memory',
    description: 'Durable memory and reusable skills shared across chats, projects, and missions.',
    status: 'planned',
    permissions: ['memory_read', 'memory_write', 'filesystem_read'],
    safetyNotes: ['No memory store implemented yet.'],
    builtIn: true
  },
  {
    id: 'chroma-memory',
    name: 'Chroma Memory',
    version: '0.1.0',
    kind: 'memory',
    description: 'Vector memory backend (mission/skill/project memory, semantic search). Phase 35 only diagnoses whether Python + chromadb are available; no ingestion or embeddings.',
    status: 'planned',
    permissions: ['memory_read', 'memory_write', 'network', 'filesystem_read'],
    settingsSchema: { chromaEndpoint: { type: 'string', label: 'Chroma HTTP endpoint (optional)' } },
    safetyNotes: [
      'No documents are ingested and no embeddings are stored in Phase 35.',
      'Chroma is never auto-started; a future opt-in will manage it.'
    ],
    builtIn: true
  },
  {
    id: 'browser-automation',
    name: 'Browser / Chrome Automation',
    version: '0.1.0',
    kind: 'browser',
    description: 'Controlled browser tasks for research, web-app testing, and screenshot-assisted debugging. Phase 35 only detects whether Chrome/Chromium is installed.',
    status: 'planned',
    permissions: ['browser', 'network', 'filesystem_read'],
    safetyNotes: [
      'No browser profile data (cookies/history/passwords) is ever read.',
      'No website is automated in Phase 35 — detection only.'
    ],
    builtIn: true
  },
  {
    id: 'testlab-extensions',
    name: 'Test Lab Extensions',
    version: '1.0.0',
    kind: 'tool',
    description: 'The existing sandboxed generate-and-run Test Lab, exposed as an extensible surface.',
    status: 'built_in',
    permissions: ['filesystem_read', 'terminal_read'],
    safetyNotes: ['Built-in; runs in the existing Test Lab sandbox.'],
    builtIn: true
  },
  {
    id: 'mission-runners',
    name: 'Mission Engine Runners',
    version: '0.1.0',
    kind: 'automation',
    description: 'Planner / executor / reviewer / tester / committer runners for the Mission Engine — preview-only today.',
    status: 'planned',
    permissions: ['terminal_write', 'git_write', 'filesystem_write', 'network'],
    safetyNotes: ['No Run Mission in Phase 35.', 'Execution would be gated behind explicit per-capability approval.'],
    builtIn: true
  },
  {
    id: 'controller-api',
    name: 'API / Controller',
    version: '1.0.0',
    kind: 'integration',
    description: 'The optional local controller HTTP API itself. Status follows whether the controller is enabled and running.',
    status: 'built_in',
    permissions: ['controller_api', 'network'],
    docsUrl: 'docs/controller-api.md',
    safetyNotes: ['Loopback-only by default, token-protected, read-only in Phase 35.'],
    builtIn: true
  },
  {
    id: 'git-cli',
    name: 'Git',
    version: '1.0.0',
    kind: 'tool',
    description: 'Inspect history, diffs, branches, and repository state with the standard Git CLI.',
    status: 'unavailable',
    permissions: ['filesystem_read', 'filesystem_write', 'terminal_read', 'git_read', 'git_write'],
    diagnosticCommand: { command: 'git', args: ['--version'] },
    capabilityHint: 'Use git for repository history, diffs, status, and local checkpoints. Never push unless the user explicitly asks.',
    installHint: 'Install Apple Command Line Tools or run: brew install git',
    docsUrl: 'https://git-scm.com/docs',
    safetyNotes: ['Workspace scope still applies.', 'Remote writes require explicit user intent.'],
    builtIn: true
  },
  {
    id: 'ripgrep-tool',
    name: 'ripgrep',
    version: '1.0.0',
    kind: 'tool',
    description: 'Search project text quickly while respecting ignore files and hidden repository rules.',
    status: 'unavailable',
    permissions: ['filesystem_read', 'terminal_read'],
    diagnosticCommand: { command: 'rg', args: ['--version'] },
    capabilityHint: 'Prefer rg for fast project-wide text and file searches.',
    installHint: 'Install with: brew install ripgrep',
    docsUrl: 'https://github.com/BurntSushi/ripgrep',
    safetyNotes: ['Read-only search tool.'],
    builtIn: true
  },
  {
    id: 'jq-tool',
    name: 'jq',
    version: '1.0.0',
    kind: 'tool',
    description: 'Query, filter, transform, and validate JSON from the local command line.',
    status: 'unavailable',
    permissions: ['filesystem_read', 'terminal_read', 'terminal_write'],
    diagnosticCommand: { command: 'jq', args: ['--version'] },
    capabilityHint: 'Use jq for precise JSON inspection and transformation.',
    installHint: 'Install with: brew install jq',
    docsUrl: 'https://jqlang.org/manual/',
    safetyNotes: ['Output redirection remains governed by Workspace permissions.'],
    builtIn: true
  },
  {
    id: 'sqlite-tool',
    name: 'SQLite CLI',
    version: '1.0.0',
    kind: 'tool',
    description: 'Inspect schemas and query project-local SQLite databases without a separate server.',
    status: 'unavailable',
    permissions: ['filesystem_read', 'filesystem_write', 'terminal_read', 'terminal_write'],
    diagnosticCommand: { command: 'sqlite3', args: ['--version'] },
    capabilityHint: 'Use sqlite3 for project-local database inspection; back up data before schema mutations.',
    installHint: 'Bundled with macOS, or install with: brew install sqlite',
    docsUrl: 'https://sqlite.org/cli.html',
    safetyNotes: ['Database writes must stay inside the selected project.', 'Destructive queries require explicit approval.'],
    builtIn: true
  },
  {
    id: 'ffmpeg-tool',
    name: 'FFmpeg',
    version: '1.0.0',
    kind: 'tool',
    description: 'Inspect, convert, trim, and encode local audio and video assets.',
    status: 'unavailable',
    permissions: ['filesystem_read', 'filesystem_write', 'terminal_read', 'terminal_write'],
    diagnosticCommand: { command: 'ffmpeg', args: ['-version'] },
    capabilityHint: 'Use ffmpeg for audio/video inspection and conversion, preserving source files unless replacement is requested.',
    installHint: 'Install with: brew install ffmpeg',
    docsUrl: 'https://ffmpeg.org/documentation.html',
    safetyNotes: ['Media output remains project-scoped.', 'Do not overwrite source assets without user intent.'],
    builtIn: true
  },
  {
    id: 'pandoc-tool',
    name: 'Pandoc',
    version: '1.0.0',
    kind: 'tool',
    description: 'Convert Markdown, HTML, DOCX, EPUB, and other document formats.',
    status: 'unavailable',
    permissions: ['filesystem_read', 'filesystem_write', 'terminal_read', 'terminal_write'],
    diagnosticCommand: { command: 'pandoc', args: ['--version'] },
    capabilityHint: 'Use pandoc for document conversion; verify generated output and preserve the editable source.',
    installHint: 'Install with: brew install pandoc',
    docsUrl: 'https://pandoc.org/MANUAL.html',
    safetyNotes: ['Generated documents stay in the selected workspace.'],
    builtIn: true
  },
  {
    id: 'poppler-tool',
    name: 'Poppler PDF Tools',
    version: '1.0.0',
    kind: 'tool',
    description: 'Extract text, inspect metadata, and render pages from PDF documents.',
    status: 'unavailable',
    permissions: ['filesystem_read', 'filesystem_write', 'terminal_read', 'terminal_write'],
    diagnosticCommand: { command: 'pdftotext', args: ['-v'] },
    capabilityHint: 'Use Poppler tools such as pdftotext and pdftoppm for PDF inspection and rendering.',
    installHint: 'Install with: brew install poppler',
    docsUrl: 'https://poppler.freedesktop.org/',
    safetyNotes: ['Never send document contents outside the selected model flow.'],
    builtIn: true
  },
  {
    id: 'imagemagick-tool',
    name: 'ImageMagick',
    version: '1.0.0',
    kind: 'tool',
    description: 'Resize, optimize, inspect, and convert local image assets.',
    status: 'unavailable',
    permissions: ['filesystem_read', 'filesystem_write', 'terminal_read', 'terminal_write'],
    diagnosticCommand: { command: 'magick', args: ['--version'] },
    capabilityHint: 'Use ImageMagick for deterministic image inspection, resizing, optimization, and format conversion.',
    installHint: 'Install with: brew install imagemagick',
    docsUrl: 'https://imagemagick.org/script/command-line-processing.php',
    safetyNotes: ['Keep original image assets unless replacement is explicitly requested.'],
    builtIn: true
  },
  {
    id: 'tesseract-tool',
    name: 'Tesseract OCR',
    version: '1.0.0',
    kind: 'tool',
    description: 'Extract text from screenshots, scans, and image-based documents locally.',
    status: 'unavailable',
    permissions: ['filesystem_read', 'filesystem_write', 'terminal_read', 'terminal_write'],
    diagnosticCommand: { command: 'tesseract', args: ['--version'] },
    capabilityHint: 'Use tesseract for local OCR and clearly mark uncertain recognition results.',
    installHint: 'Install with: brew install tesseract',
    docsUrl: 'https://tesseract-ocr.github.io/tessdoc/',
    safetyNotes: ['OCR remains local and project-scoped.'],
    builtIn: true
  },
  {
    id: 'graphviz-tool',
    name: 'Graphviz',
    version: '1.0.0',
    kind: 'tool',
    description: 'Render architecture, dependency, and process diagrams from DOT source.',
    status: 'unavailable',
    permissions: ['filesystem_read', 'filesystem_write', 'terminal_read', 'terminal_write'],
    diagnosticCommand: { command: 'dot', args: ['-V'] },
    capabilityHint: 'Use Graphviz DOT for reproducible architecture and relationship diagrams.',
    installHint: 'Install with: brew install graphviz',
    docsUrl: 'https://graphviz.org/documentation/',
    safetyNotes: ['Generated diagrams stay in the selected workspace.'],
    builtIn: true
  },
  {
    id: 'python-runtime',
    name: 'Python',
    version: '1.0.0',
    kind: 'tool',
    description: 'Run project scripts, data transformations, tests, and document tooling with Python 3.',
    status: 'unavailable',
    permissions: ['filesystem_read', 'filesystem_write', 'terminal_read', 'terminal_write'],
    diagnosticCommand: { command: 'python3', args: ['--version'] },
    capabilityHint: 'Use python3 for existing project scripts and bounded automation; prefer project environments and declared dependencies.',
    installHint: 'Install with: brew install python',
    docsUrl: 'https://docs.python.org/3/',
    safetyNotes: ['Do not install global packages silently.', 'Respect the project environment and lock files.'],
    builtIn: true
  },
  {
    id: 'node-runtime',
    name: 'Node.js',
    version: '1.0.0',
    kind: 'tool',
    description: 'Run JavaScript and TypeScript project scripts, builds, tests, and local tooling.',
    status: 'unavailable',
    permissions: ['filesystem_read', 'filesystem_write', 'terminal_read', 'terminal_write'],
    diagnosticCommand: { command: 'node', args: ['--version'] },
    capabilityHint: 'Use Node.js through the project package manager and existing scripts; respect the lockfile.',
    installHint: 'Install with: brew install node',
    docsUrl: 'https://nodejs.org/docs/latest/api/',
    safetyNotes: ['Do not install global packages silently.', 'Use the repository lockfile and scripts.'],
    builtIn: true
  },
  {
    id: 'git-lfs-tool',
    name: 'Git LFS',
    version: '1.0.0',
    kind: 'integration',
    description: 'Manage large repository assets through Git pointer files and remote object storage.',
    status: 'unavailable',
    permissions: ['filesystem_read', 'filesystem_write', 'terminal_read', 'git_read', 'git_write', 'network'],
    diagnosticCommand: { command: 'git-lfs', args: ['version'] },
    capabilityHint: 'Use Git LFS only when the repository already uses it or the user requests large-file tracking.',
    installHint: 'Install with: brew install git-lfs',
    docsUrl: 'https://git-lfs.com/',
    safetyNotes: ['Tracking changes alter .gitattributes and require explicit user intent.', 'Never push automatically.'],
    builtIn: true
  },
  {
    id: 'shellcheck-tool',
    name: 'ShellCheck',
    version: '1.0.0',
    kind: 'tool',
    description: 'Statically analyze Bash and POSIX shell scripts for correctness and portability issues.',
    status: 'unavailable',
    permissions: ['filesystem_read', 'terminal_read'],
    diagnosticCommand: { command: 'shellcheck', args: ['--version'] },
    capabilityHint: 'Run ShellCheck when editing shell scripts and resolve findings proportionally to the task.',
    installHint: 'Install with: brew install shellcheck',
    docsUrl: 'https://www.shellcheck.net/',
    safetyNotes: ['Read-only static analysis.'],
    builtIn: true
  },
  {
    id: 'yt-dlp-tool',
    name: 'yt-dlp',
    version: '1.0.0',
    kind: 'tool',
    description: 'Inspect and download user-authorized online audio or video sources for local processing.',
    status: 'unavailable',
    permissions: ['filesystem_write', 'terminal_read', 'terminal_write', 'network'],
    diagnosticCommand: { command: 'yt-dlp', args: ['--version'] },
    capabilityHint: 'Use yt-dlp only for user-authorized sources and requested media workflows; respect site terms and copyright.',
    installHint: 'Install with: brew install yt-dlp',
    docsUrl: 'https://github.com/yt-dlp/yt-dlp',
    safetyNotes: ['Require user-authorized sources.', 'Respect copyright, access controls, and site terms.'],
    builtIn: true
  }
]
