import { renameSync, writeFileSync } from 'fs'
import type { ResearchDocument } from '../document'
import { sourceCitationLabel } from '../document'
import { researchArtifactPath } from '../workspace'

export function renderResearchMarkdown(document: ResearchDocument): string {
  const lines: string[] = [
    `# ${document.title}`,
    '',
    document.subtitle,
    '',
    `> Generated by ${document.requestedBy} on ${new Date(document.generatedAt).toISOString()}.`,
    `> Depth: ${document.depthLabel} · Provider: ${document.providerLabel} · Model: ${document.modelLabel}`,
    '',
    '## Executive summary',
    '',
    document.executiveSummary,
    ''
  ]

  for (const section of document.sections) {
    lines.push(`## ${section.title}`, '', section.body.trim(), '')
    if (section.claims.length > 0) {
      lines.push('### Evidence ledger', '')
      for (const claim of section.claims) {
        const refs = claim.evidence
          .map((item) => document.sources.findIndex((source) => source.id === item.sourceId))
          .filter((index) => index >= 0)
          .map((index) => `[${index + 1}](#source-${index + 1})`)
          .join(', ')
        lines.push(`- **${claim.status}:** ${claim.text}${refs ? ` ${refs}` : ' _(no verified citation)_'} `)
      }
      lines.push('')
    }
  }

  if (document.methodology.length > 0 || document.verificationCriteria.length > 0) {
    lines.push('## Methodology', '')
    for (const item of document.methodology) lines.push(`- ${item}`)
    if (document.verificationCriteria.length > 0) {
      lines.push('', '### Verification criteria', '')
      for (const item of document.verificationCriteria) lines.push(`- ${item}`)
    }
    lines.push('')
  }

  lines.push('## Sources', '')
  document.sources.forEach((source, index) => {
    lines.push(`<a id="source-${index + 1}"></a>`)
    lines.push(`${sourceCitationLabel(source, index)}${source.publishedAt ? ` Published ${source.publishedAt}.` : ''} Accessed ${new Date(source.accessedAt).toISOString().slice(0, 10)}.`)
    lines.push('')
  })
  return `${lines.join('\n').trim()}\n`
}

export function exportResearchMarkdown(
  workspaceDir: string,
  document: ResearchDocument
): string {
  const path = researchArtifactPath(workspaceDir, document.title, 'md')
  const partial = `${path}.partial`
  writeFileSync(partial, renderResearchMarkdown(document), 'utf8')
  renameSync(partial, path)
  return path
}
