import { mkdirSync, renameSync, writeFileSync } from 'fs'
import { basename, dirname, extname, join } from 'path'
import type { ResearchDocument } from '../document'
import { sourceCitationLabel } from '../document'
import {
  renderResearchVisualSvg,
  researchVisualCitationNumbers
} from '../visual-evidence'
import { researchArtifactPath } from '../workspace'
import { markdownAnchor } from './design'

export function renderResearchMarkdown(
  document: ResearchDocument,
  visualAssetPrefix?: string
): string {
  const reservedAnchors = [
    'executive-summary',
    'visual-evidence',
    'methodology',
    'sources',
    ...document.sources.map((_, index) => `source-${index + 1}`)
  ]
  const sectionAnchors = uniqueSectionAnchors(
    document.sections.map((section) => section.title),
    reservedAnchors
  )
  const lines: string[] = [
    `# ${document.title}`,
    '',
    `*${document.subtitle}*`,
    '',
    '| Report details | |',
    '| --- | --- |',
    `| Generated by | ${escapeMarkdownTableCell(document.requestedBy)} |`,
    `| Generated | ${new Date(document.generatedAt).toISOString()} |`,
    `| Research depth | ${escapeMarkdownTableCell(document.depthLabel)} |`,
    `| Provider | ${escapeMarkdownTableCell(document.providerLabel)} |`,
    `| Model | ${escapeMarkdownTableCell(document.modelLabel)} |`,
    `| Evidence base | ${document.sources.length} sources · ${document.sections.reduce((total, section) => total + section.claims.length, 0)} display claims |`,
    '',
    '---',
    '',
    '## Contents',
    '',
    '- [Executive summary](#executive-summary)',
    ...document.sections.map((section, index) => `- [${section.title}](#${sectionAnchors[index]})`),
    ...(document.visuals.length > 0 ? ['- [Visual evidence](#visual-evidence)'] : []),
    ...(document.methodology.length > 0 || document.verificationCriteria.length > 0 ? ['- [Methodology](#methodology)'] : []),
    '- [Sources](#sources)',
    '',
    '<a id="executive-summary"></a>',
    '',
    '## Executive summary',
    '',
    document.executiveSummary,
    ''
  ]

  for (const [sectionIndex, section] of document.sections.entries()) {
    lines.push(`<a id="${sectionAnchors[sectionIndex]}"></a>`, '', `## ${section.title}`, '', section.body.trim(), '')
    if (section.claims.length > 0) {
      lines.push('### Evidence ledger', '')
      for (const claim of section.claims) {
        const refs = claim.evidence
          .map((item) => document.sources.findIndex((source) => source.id === item.sourceId))
          .filter((index) => index >= 0)
          .map((index) => `[${index + 1}](#source-${index + 1})`)
          .join(', ')
        lines.push(`- **${claim.status}:** ${claim.text}${refs ? ` ${refs}` : ' _(no verified citation)_'} `)
      }
      lines.push('')
    }
  }

  if (document.visuals.length > 0) {
    lines.push('<a id="visual-evidence"></a>', '', '## Visual evidence', '')
    document.visuals.forEach((visual, index) => {
      const citations = researchVisualCitationNumbers(visual.provenance.sourceIds, document.sources)
      const refs = citations.map((number) => `[${number}](#source-${number})`).join(', ')
      lines.push(`### Figure ${index + 1}. ${visual.title}`, '')
      if (visualAssetPrefix) {
        lines.push(`![${escapeMarkdownAlt(visual.altText)}](${visualAssetPrefix}/${visual.id}.svg)`, '')
      }
      lines.push(`*${visual.caption}${refs ? ` Sources: ${refs}.` : ''}*`, '')
      if (visual.kind === 'evidence-table' && visual.columns && visual.rows) {
        lines.push(
          `| ${visual.columns.join(' | ')} |`,
          `| ${visual.columns.map(() => '---').join(' | ')} |`
        )
        for (const row of visual.rows) {
          lines.push(`| ${row.cells.map(escapeMarkdownTableCell).join(' | ')} |`)
        }
        lines.push('')
      }
      lines.push(`Provenance: ${visual.provenance.method}; generated ${new Date(visual.provenance.generatedAt).toISOString()}.`, '')
    })
  }

  if (document.methodology.length > 0 || document.verificationCriteria.length > 0) {
    lines.push('<a id="methodology"></a>', '', '## Methodology', '')
    for (const item of document.methodology) lines.push(`- ${item}`)
    if (document.verificationCriteria.length > 0) {
      lines.push('', '### Verification criteria', '')
      for (const item of document.verificationCriteria) lines.push(`- ${item}`)
    }
    lines.push('')
  }

  lines.push('<a id="sources"></a>', '', '## Sources', '')
  document.sources.forEach((source, index) => {
    lines.push(`<a id="source-${index + 1}"></a>`)
    const citation = sourceCitationLabel(source, index).replace(/^\[\d+\]\s*/, '')
    lines.push(`${index + 1}. ${citation}${source.publishedAt ? ` Published ${source.publishedAt}.` : ''} Accessed ${new Date(source.accessedAt).toISOString().slice(0, 10)}.`)
    lines.push('')
  })
  return `${lines.join('\n').trim()}\n`
}

function uniqueSectionAnchors(titles: string[], reservedAnchors: string[]): string[] {
  const used = new Set(reservedAnchors)
  return titles.map((title) => {
    const base = markdownAnchor(title)
    let anchor = base
    let suffix = 2
    while (used.has(anchor)) anchor = `${base}-${suffix++}`
    used.add(anchor)
    return anchor
  })
}

export function exportResearchMarkdown(
  workspaceDir: string,
  document: ResearchDocument,
  outputPath?: string
): string {
  const path = outputPath ?? researchArtifactPath(workspaceDir, document.title, 'md')
  const partial = `${path}.partial`
  const assetDirName = `${basename(path, extname(path))}-assets`
  const assetDir = join(dirname(path), assetDirName)
  mkdirSync(assetDir, { recursive: true })
  for (const visual of document.visuals) {
    writeFileSync(join(assetDir, `${visual.id}.svg`), renderResearchVisualSvg(visual), 'utf8')
  }
  writeFileSync(partial, renderResearchMarkdown(document, `./${assetDirName}`), 'utf8')
  renameSync(partial, path)
  return path
}

function escapeMarkdownAlt(value: string): string {
  return value.replace(/[\[\]]/g, '').replace(/\s+/g, ' ').trim()
}

function escapeMarkdownTableCell(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ').trim()
}
