import { app, ipcMain } from 'electron'
import { execFile } from 'child_process'
import { existsSync, readFileSync } from 'fs'
import { join } from 'path'

// Phase 42 (Remote Ollama): expose which commit/version this app was built from,
// so the Mac can tell whether the installed app is behind GitHub main.

export interface BuildInfo {
  version: string
  gitCommit: string
  gitCommitFull: string
  gitBranch: string
  buildDate: string
  buildMode: string
  platform: string
  packaged: boolean
}

let cached: BuildInfo | null = null

function readBuildInfoFile(): Partial<BuildInfo> {
  // build-info.json is generated by scripts/gen-build-info.js and bundled via the
  // electron-builder `files` list, so it sits next to the app's source in the asar.
  const candidates = [join(app.getAppPath(), 'build-info.json'), join(process.cwd(), 'build-info.json')]
  for (const path of candidates) {
    try {
      if (existsSync(path)) return JSON.parse(readFileSync(path, 'utf8')) as Partial<BuildInfo>
    } catch {
      /* ignore malformed/unreadable */
    }
  }
  return {}
}

export function getBuildInfo(): BuildInfo {
  if (cached) return cached
  const file = readBuildInfoFile()
  cached = {
    version: file.version || app.getVersion(),
    gitCommit: file.gitCommit || 'unknown',
    gitCommitFull: file.gitCommitFull || 'unknown',
    gitBranch: file.gitBranch || 'unknown',
    buildDate: file.buildDate || 'unknown',
    buildMode: file.buildMode || (app.isPackaged ? 'production' : 'dev'),
    platform: process.platform,
    packaged: app.isPackaged
  }
  return cached
}

/** Read-only `git` query for the dev repo (used by the currency check). */
function git(cwd: string, args: string[], timeoutMs = 15_000): Promise<string> {
  return new Promise((resolve) => {
    execFile('git', ['-C', cwd, ...args], { timeout: timeoutMs, windowsHide: true }, (err, stdout) => {
      resolve(err ? '' : (stdout ?? '').trim())
    })
  })
}

export interface AppCurrency {
  /** 'git' when running from a source checkout; 'packaged' otherwise. */
  mode: 'git' | 'packaged'
  buildCommit: string
  repoHead?: string
  remoteMainHead?: string
  /** commits the build is behind origin/main (only meaningful in a git checkout). */
  behindBy?: number
  isCurrent?: boolean
  note: string
  checkedAt: number
}

/**
 * Compare the build's commit to origin/main. In a source checkout we can fetch and
 * count; for a packaged app with no repo we just report the embedded commit.
 */
export async function getAppCurrency(fetch: boolean): Promise<AppCurrency> {
  const build = getBuildInfo()
  const cwd = app.getAppPath()
  const isRepo = (await git(cwd, ['rev-parse', '--is-inside-work-tree'])) === 'true'

  if (!isRepo) {
    return {
      mode: 'packaged',
      buildCommit: build.gitCommit,
      note: `Installed build is ${build.version} @ ${build.gitCommit}. To compare against GitHub main, check from the source checkout (Settings → Update).`,
      checkedAt: Date.now()
    }
  }

  const top = (await git(cwd, ['rev-parse', '--show-toplevel'])) || cwd
  if (fetch) await git(top, ['fetch', 'origin', '--quiet'], 45_000)
  const repoHead = await git(top, ['rev-parse', '--short', 'HEAD'])
  const remoteMainHead = await git(top, ['rev-parse', '--short', 'origin/main'])
  let behindBy: number | undefined
  if (remoteMainHead) {
    const counts = await git(top, ['rev-list', '--left-right', '--count', 'HEAD...origin/main'])
    const parts = counts.split(/\s+/).map((n) => Number(n))
    behindBy = Number.isFinite(parts[1]) ? parts[1] : undefined
  }
  const isCurrent = behindBy === 0
  return {
    mode: 'git',
    buildCommit: build.gitCommit,
    repoHead,
    remoteMainHead,
    behindBy,
    isCurrent,
    note: isCurrent
      ? 'Source checkout is up to date with origin/main.'
      : behindBy && behindBy > 0
        ? `Source checkout is ${behindBy} commit(s) behind origin/main — rebuild/refresh the app to update.`
        : 'Could not determine how current the checkout is.',
    checkedAt: Date.now()
  }
}

export function registerBuildInfoIpc(): void {
  ipcMain.handle('app:getBuildInfo', (): BuildInfo => getBuildInfo())
  ipcMain.handle('app:getCurrency', async (_event, fetch: unknown): Promise<AppCurrency> => getAppCurrency(fetch === true))
}
